### ISSUE TITLE
How do I open a matlab instance in the buffer?

### ISSUE THREAD

**Issue by Jaehaks** [MIBismuth/matlab.nvim#1]
Thank you for your efforts, 

When I input command `:MatlabCliOpen`, vnew buffer opens but matlab instance cannot open in the buffer.
It opens with external window like this instead of that
![image](https://github.com/MIBismuth/matlab.nvim/assets/26200835/97dc278f-f88c-467b-9311-56f9ac8e8885)

I'm Windows 10 User and use MATLAB 2018a. 
Could you notice what i missed?

**Comment by MIBismuth** [comment]
Hello!
Thanks for bringing this issue to my attention, as I'm not a Windows user I had no idea about this behavior.

I looked it up and apparently on Windows when you launch Matlab from the command prompt with the `-nodesktop -nosplash` options it opens that command window. This issue is described in this post https://stackoverflow.com/questions/69411006/how-to-launch-matlab-without-a-desktop-in-windows

I'm not sure if there is a workaround that prevents this window from opening, they mention the `-batch` option, but that seems to only run a single command and not the REPL. I'll have to look into that.

Do the other commands from the plugin like `:MatlabCliRunCell` still work on this external window? I would imagine not.

**Comment by Jaehaks** [comment]
@MIBismuth 

I  realised that matlab cannot support execution through command prompt in windows.  
It is possible to run on a file-by-file basis, but it does not support interactive mode as linux does. 
Thank you your reply :)
